nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs

enableNetwork: false
enableStrictSsl: true

networkSettings:
  "registry.yarnpkg.com":
    enableNetwork: true
  "registry.npmjs.org":
    enableNetwork: true
