name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
    - name: Install
      run: npm install
    - name: Lint
      run: |
        npm run lint -- --no-fix
        DEBUG="lockfile-lint,validate-host-manager" npx lockfile-lint --path package-lock.json --validate-https --allowed-hosts npm
    - name: Test
      run: |
        npm run coverage:unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        fail_ci_if_error: false
    - name: Build
      run: npm run build

