name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  unit-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Install
        run: yarn install

      - name: Lint
        env:
          NODE_ENV: production
        run: |
          yarn run lint .

      - name: Test
        run: |
          yarn run coverage:unit --colors

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          name: '${{ github.job }}'
          flags: unittests
          fail_ci_if_error: false

      - name: Build
        run: yarn run build


  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [firefox, chrome]
        type: [e2e, component]
# TODO: re-enable once macos build is stable #590
#         include:
#           - os: macos-latest
#             browser: edge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Test
        uses: cypress-io/github-action@v5
        with:
          start: yarn run serve
          wait-on: http://localhost:5173/
          config-file: cypress.config.js
          component: ${{ matrix.type == 'component' }}
          spec: |
            tests/e2e/**/*
            cypress/component/*
            cypress/component/**/*
          browser: ${{ matrix.browser }}
        env:
          CYPRESS_baseUrl: http://localhost:5173/

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          name: '${{ github.job }} ${{ matrix.os }} ${{ matrix.browser }} ${{ matrix.type }}'
          flags: ${{ matrix.type }}
          fail_ci_if_error: false
